Repository STORM-IRIT/Radium-Engine, pull requests merged in 2018-05, with the labels that each got.

#312 Fix MeshFeatureTrackingPlugin sphere ;
  Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp
  Plugins/MeshFeatureTracking/src/MeshFeatureTrackingPlugin.cpp
Labels: [master-v1]

#317 Fix issue Crash on reset scene #314
  src/GuiBase/Viewer/CameraInterface.cpp
  src/GuiBase/Viewer/Viewer.cpp
Labels: [master-v1], bug

#315 Fix function export in library ;
  Plugins/Animation/src/AnimationComponent.cpp
  Plugins/Animation/src/Drawing/SkeletonBoneDrawable.cpp
  src/Core/Animation/Handle/Cage.cpp
  src/Core/Animation/Handle/Cage.hpp
  src/Core/Animation/Handle/Handle.cpp
  src/Core/Animation/Handle/Handle.hpp
  src/Core/Animation/Handle/Handle.inl
  src/Core/Animation/Handle/PointCloud.hpp
  src/Core/Animation/Handle/Skeleton.cpp
  src/Core/Animation/Handle/Skeleton.hpp
  src/Core/Animation/Handle/SkeletonUtils.cpp
  src/Core/Animation/Handle/SkeletonUtils.hpp
Labels: Build System, Core, High priority, [master-v1]
