Repository STORM-IRIT/Radium-Engine, pull requests merged in 2019-12, with the labels that each got.

#475 Fix use of transforms on aabb ;
  src/Core/Geometry/Obb.hpp
  src/Engine/Renderer/RenderObject/RenderObject.cpp
  tests/unittest/CMakeLists.txt
  tests/unittest/Core/obb.cpp
Labels: Core, High priority, Ready to merge, bug

#477 Unique box checking
  src/GuiBase/TreeModel/TreeModel.cpp
  src/GuiBase/TreeModel/TreeModel.hpp
Labels: Ready to merge

#474 Conf fix
  .gitignore
Labels: Build System, Ready to merge
