Repository STORM-IRIT/Radium-Engine, pull requests merged in 2019-06, with the labels that each got.

#428 Fix Codacy issues in PR #424
  Applications/HelloRadium/minimalradium.hpp
  Applications/SimpleSubdivideExample/main.cpp
  Plugins/Animation/src/AnimationComponent.cpp
  Plugins/Animation/src/AnimationComponent.hpp
  Plugins/Animation/src/AnimationPlugin.cpp
  Plugins/Animation/src/AnimationPlugin.hpp
  Plugins/Dummy/src/DummyPlugin.hpp
  Plugins/Dummy/src/DummyTask.hpp
  Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp
  Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.hpp
  Plugins/MeshFeatureTracking/src/MeshFeatureTrackingPlugin.cpp
  Plugins/MeshFeatureTracking/src/MeshFeatureTrackingPlugin.hpp
  Plugins/Skinning/src/SkinningComponent.cpp
  Plugins/Skinning/src/SkinningComponent.hpp
  Plugins/Skinning/src/SkinningPlugin.hpp
  src/Core/Animation/BulgeCorrection.hpp
  src/Core/Animation/Cage.hpp
  src/Core/Animation/Handle.hpp
  src/Core/Animation/KeyPose.hpp
  src/Core/Animation/KeyRotation.hpp
  src/Core/Animation/KeyScaling.hpp
  src/Core/Animation/KeyTransform.hpp
  src/Core/Animation/KeyTranslation.hpp
  src/Core/Animation/Skeleton.hpp
  src/Core/Asset/AnimationData.hpp
  src/Core/Asset/AssetData.hpp
  src/Core/Containers/AdjacencyList.hpp
  src/Core/Containers/BVH.hpp
  src/Core/Containers/Iterators.hpp
  src/Core/Geometry/Curve2D.hpp
  src/Core/Geometry/Frustum.hpp
  src/Core/Geometry/MeshPrimitives.cpp
  src/Core/Geometry/PolyLine.hpp
  src/Core/Geometry/Spline.hpp
  src/Core/Tasks/TaskQueue.cpp
  src/Core/Utils/Attribs.hpp
  src/Core/Utils/Color.hpp
  src/Core/Utils/Index.hpp
  src/Core/Utils/Index.inl
  src/Engine/Renderer/Renderer.hpp
  src/GuiBase/Event/EventEnums.hpp
  src/GuiBase/Event/KeyEvent.hpp
  src/GuiBase/Event/MouseEvent.hpp
  src/GuiBase/Viewer/CameraInterface.hpp
  src/GuiBase/Viewer/TrackballCamera.cpp
  src/GuiBase/Viewer/Viewer.cpp
  src/GuiBase/Viewer/Viewer.hpp
  src/GuiBase/Viewer/WindowQt.hpp
  src/PluginBase/RadiumPluginInterface.hpp
  tests/Tests.hpp
Labels: code style

#420 Checkbox in the engine object tree for visibility
  Applications/MainApplication/Gui/MainWindow.cpp
  Applications/MainApplication/Gui/MainWindow.hpp
  Applications/MainApplication/Gui/ui/MainWindow.ui
  src/GuiBase/TreeModel/EntityTreeModel.cpp
  src/GuiBase/TreeModel/EntityTreeModel.hpp
  src/GuiBase/TreeModel/TreeModel.cpp
  src/GuiBase/TreeModel/TreeModel.hpp
Labels: Review In Progress, [master-v1], enhancement

#434 Fix typo making the skinning plugin crash in debug ;
  Plugins/Skinning/src/SkinningComponent.cpp
Labels: High priority, Plug : Skinning, bug

#441 fix issue #435 - Colors: compilation issues
  src/Core/Utils/Color.hpp
Labels: High priority
