Repository STORM-IRIT/Radium-Engine, pull requests merged in 2019-07, with the labels that each got.

#444 Fix #443
  Applications/MainApplication/Gui/MainWindow.cpp
  Applications/MainApplication/Gui/ui/MainWindow.ui
  Assets/Images/screenshot.png
  icons.qrc
  src/Engine/ItemModel/ItemEntry.cpp
  src/GuiBase/BaseApplication.cpp
  src/GuiBase/BaseApplication.hpp
  src/GuiBase/Viewer/Gizmo/GizmoManager.cpp
  src/GuiBase/Viewer/Gizmo/GizmoManager.hpp
Labels: Feature Request, MainApp, bug

#450 Add PluginBase to Radium exported targets.
  cmake/FindRadium.cmake
Labels: Build System, bug

#458 Add configuration file for probot/stale
  .github/stale.yml
Labels: enhancement
