Repository STORM-IRIT/Radium-Engine, pull requests merged in 2020-04, with the labels that each got.

#520 Fix #519
  src/Engine/Renderer/RenderTechnique/RenderTechnique.cpp
Labels: Engine, High priority, bug

#522 Fix compilation error with Qt version < 5.10.0
  src/GuiBase/Utils/KeyMappingManager.cpp
Labels: High priority, bug

#534 [cmake] Export dependency to OpenMP only when required
  cmake/Config.cmake.in
Labels: Build System, High priority, bug
