Repository STORM-IRIT/Radium-Engine, pull requests merged in 2020-11, with the labels that each got.

#554 Allow to use locally installed dependencies instead of the one bundled with Radium
  .github/workflows/formatter.yml
  cmake/ExternalInclude.cmake
  cmake/externalFunc.cmake
  cmake/radium_setup_functions.cmake
  doc/basics/compilation.md
  doc/developer/buildchain.md
  external/CMakeLists.txt
  external/Core/CMakeLists.txt
  external/Core/package.cmake
  external/Core/patches/cpplocate.patch
  external/Engine/CMakeLists.txt
  external/Engine/package.cmake
  external/Engine/patches/glbinding.patch
  external/Engine/patches/globjects.patch
  external/IO/CMakeLists.txt
  external/IO/package.cmake
  scripts/list_dep.py
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Core/external/CMakeLists.txt
  src/Core/external/package.cmake
  src/Engine/CMakeLists.txt
  src/Engine/external/CMakeLists.txt
  src/Engine/external/package.cmake
  src/IO/CMakeLists.txt
  src/IO/external/CMakeLists.txt
  src/IO/external/package.cmake
Labels: Build System, WIP

#609 Point cloud parameter provider
  Shaders/Points/PointCloud.geom.glsl
  src/Engine/Component/GeometryComponent.hpp
  src/Engine/Renderer/Renderers/ForwardRenderer.cpp
  tests/ExampleApps/SimpleSimulationApp/main.cpp
Labels: Engine, Feature Request, [master-v1], enhancement

#615 fix issue #584
  external/Engine/CMakeLists.txt
  external/Engine/package.cmake
Labels: Build System, bug

#617 Message format
  CMakeLists.txt
  cmake/cleanCppExtensions.cmake
  cmake/externalFunc.cmake
  cmake/radium_setup_functions.cmake
  cmake/sanitizers.cmake
  cmake/useGoldLinker.cmake
  doc/CMakeLists.txt
  external/Core/CMakeLists.txt
  external/Engine/CMakeLists.txt
  external/IO/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/GuiBase/CMakeLists.txt
  src/IO/CMakeLists.txt
  src/PluginBase/CMakeLists.txt
  tests/CMakeLists.txt
  tests/ExampleApps/CMakeLists.txt
  tests/ExamplePluginWithLib/CMakeLists.txt
Labels: Build System

#616 Msvc2017 cmake compilation
  doc/basics/compilation.md
Labels: documentation, enhancement

#619 Configure Radium package to use externals as set at build time
  cmake/Config.cmake.in
  external/Engine/CMakeLists.txt
  external/IO/CMakeLists.txt
Labels: Build System, bug
