Repository STORM-IRIT/Radium-Engine, pull requests merged in 2020-06, with the labels that each got.

#560 [engine] Shader program refactor: use templated setUniform.
  cmake/filelistEngine.cmake
  src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
  src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp
  src/Engine/Renderer/RenderTechnique/ShaderProgram.hpp
  src/Engine/Renderer/RenderTechnique/ShaderProgram.inl
Labels: Engine, code style

#565 Fix install : patch on cginternal install procedures
  CMakeLists.txt
  cmake/Config.cmake.in
  cmake/radium_setup_functions.cmake
  src/Core/external/CMakeLists.txt
  src/Core/external/package.cmake
  src/Core/external/patches/cpplocate.patch
  src/Engine/external/CMakeLists.txt
  src/Engine/external/package.cmake
  src/Engine/external/patches/glbinding.patch
  src/Engine/external/patches/globjects.patch
Labels: Build System

#566 Fix topomesh compilation issue.
  src/Core/Geometry/TopologicalMesh.inl
Labels: bug
