Repository STORM-IRIT/Radium-Engine, pull requests merged in 2020-12, with the labels that each got.

#622 Fix typo in tinyply dir name
  cmake/Config.cmake.in
Labels: Build System, High priority, bug

#623 Definition of a Material from raw shaders set and an associated parameterProvider
  cmake/filelistEngine.cmake
  src/Engine/Renderer/Material/Material.hpp
  src/Engine/Renderer/Material/Material.inl
  src/Engine/Renderer/Material/RawShaderMaterial.cpp
  src/Engine/Renderer/Material/RawShaderMaterial.hpp
  src/Engine/Renderer/Material/RawShaderMaterial.inl
  src/Engine/Renderer/RenderTechnique/RenderParameters.hpp
  src/Engine/Renderer/RenderTechnique/ShaderConfigFactory.cpp
  src/Engine/Renderer/RenderTechnique/ShaderConfigFactory.hpp
  tests/ExampleApps/CMakeLists.txt
  tests/ExampleApps/RawShaderMaterial/main.cpp
Labels: Engine, Feature Request, tests

#626 Expose manipulator keys (protected)
  src/GuiBase/Viewer/FlightCameraManipulator.hpp
  src/GuiBase/Viewer/TrackballCameraManipulator.hpp
Labels: enhancement

#627 Add self debugging function StackTrace and better Debug messages
  cmake/filelistCore.cmake
  src/Core/Utils/StackTrace.cpp
  src/Core/Utils/StackTrace.hpp
  src/Engine/Renderer/Mesh/Mesh.hpp
  src/Engine/Renderer/OpenGL/OpenGL.hpp
  src/Engine/Renderer/RenderTechnique/ShaderProgram.cpp
Labels: Core, enhancement

#631 Attempt to make winqtdeploy more robust
  cmake/Windeployqt.cmake
Labels: Build System

#633 Allow to build Radium in Debug mode
  src/Engine/Managers/ComponentMessenger/ComponentMessenger.inl
Labels: High priority, bug

#634 Fix from codacy
  src/Core/Asset/HandleToSkeleton.cpp
  src/Core/Containers/Grid.hpp
  src/Core/Math/DualQuaternion.hpp
  src/Core/Tasks/TaskQueue.cpp
  src/Core/Tasks/TaskQueue.hpp
  src/Core/Utils/Color.hpp
  src/GuiBase/SelectionManager/SelectionManager.hpp
  src/GuiBase/TreeModel/EntityTreeModel.hpp
  src/GuiBase/TreeModel/TreeModel.hpp
Labels: bug, code style

#640 Dox fix
  .github/workflows/deploy-doc.yml
  doc/CMakeLists.txt
  doc/basics/compilation.md
  doc/developer.md
  doc/developer/cmakeutilities.md
  doc/developer/timeline.md
Labels: Build System, documentation, enhancement

#641 [cmake] make doc CMakeLists.txt working standalone.
  doc/CMakeLists.txt
Labels: Build System, bug, documentation
