Repository STORM-IRIT/Radium-Engine, pull requests merged in 2020-07, with the labels that each got.

#568 Fix cmake config scripts to support several helper libs
  cmake/radium_setup_functions.cmake
Labels: Build System, High priority, Ready to merge, bug

#559 update documentation about Rendering without using Materials
  doc/developer/material.md
Labels: documentation

#574 Reinstall external when moving install + fix external updates
  CMakeLists.txt
  cmake/externalFunc.cmake
  src/Core/Animation/KeyFramedValueInterpolators.hpp
  src/Core/external/CMakeLists.txt
  src/Engine/external/CMakeLists.txt
  tests/unittest/Core/animation.cpp
Labels: Build System, bug

#579 Force reinstalling dependencies when install dir is empty
  cmake/Config.cmake.in
  cmake/externalFunc.cmake
  src/Core/external/package.cmake
  src/Engine/external/package.cmake
  src/IO/external/package.cmake
  tests/external/CMakeLists.txt
Labels: Build System, enhancement

#583 fix #582
  src/Core/Animation/KeyFramedValueInterpolators.hpp
Labels: Core, High priority, bug, code style

#592 Update compilation documentation + Fix debugging for Microsoft OS
  cmake/radium_setup_functions.cmake
  doc/basics/compilation.md
  src/Engine/Renderer/Mesh/Mesh.hpp
Labels: Ready to merge, documentation

#593 Add windeployqt
  cmake/Windeployqt.cmake
  cmake/radium_setup_functions.cmake
Labels: Build System

#594 [hotfix] Add missing install directive for Windeployqt.cmake
  src/CMakeLists.txt
Labels: High priority, bug

#595 First step of QuadMesh
  cmake/filelistEngine.cmake
  doc/developer/mesh.md
  scripts/install-scripts-linux.sh
  src/Core/Asset/GeometryData.inl
  src/Core/Geometry/MeshPrimitives.cpp
  src/Core/Geometry/MeshPrimitives.inl
  src/Core/Geometry/RayCast.cpp
  src/Core/Geometry/TopologicalMesh.cpp
  src/Core/Geometry/TriangleMesh.hpp
  src/Core/Geometry/TriangleMesh.inl
  src/Core/Resources/Resources.cpp
  src/Core/Resources/Resources.hpp
  src/Engine/Component/GeometryComponent.cpp
  src/Engine/Component/GeometryComponent.hpp
  src/Engine/Component/GeometryComponent.inl
  src/Engine/RadiumEngine.hpp
  src/Engine/Renderer/Camera/Camera.cpp
  src/Engine/Renderer/Mesh/Mesh.cpp
  src/Engine/Renderer/Mesh/Mesh.hpp
  src/Engine/Renderer/Mesh/Mesh.inl
  src/Engine/Renderer/RenderObject/Primitives/DrawPrimitives.cpp
  src/Engine/Renderer/RenderTechnique/ShaderProgramManager.hpp
  src/Engine/Renderer/Renderers/DebugRender.cpp
  src/Engine/System/GeometrySystem.cpp
  src/IO/AssimpLoader/AssimpFileLoader.cpp
  src/IO/deprecated/OBJFileManager.cpp
  src/IO/deprecated/OFFFileManager.cpp
  tests/ExampleApps/DrawPrimitivesApp/minimalapp.hpp
  tests/ExampleApps/DrawPrimitivesApp/minimalradium.cpp
  tests/unittest/Core/mesh.cpp
  tests/unittest/Core/topomesh.cpp
Labels: Core, Engine, Feature Request, Ready to merge, enhancement

#597 Fixes issue #596 (Timeline UI)
  src/GuiBase/Timeline/Timeline.ui
Labels: GUI, Ready to merge, bug

#599 Add missing path when including Windeployqt
  cmake/radium_setup_functions.cmake
Labels: Build System, High priority, bug

#591 cmake functions documentation
  cmake/radium_setup_functions.cmake
  doc/developer.md
  doc/developer/cmakeutilities.md
  doc/developer/develWithRadium.md
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  src/Engine/CMakeLists.txt
  src/GuiBase/CMakeLists.txt
  src/IO/CMakeLists.txt
  src/PluginBase/CMakeLists.txt
  tests/ExamplePluginWithLib/Upstream/Library/CMakeLists.txt
  tests/ExamplePluginWithLib/Upstream/Library/ExampleLibrary.cpp
  tests/ExamplePluginWithLib/Upstream/Library/ExampleLibraryUpstream-Config.cmake.in
  tests/ExamplePluginWithLib/Upstream/Library/LibraryResources/welcome.txt
Labels: Build System, documentation

#602 Add missing commit of PR #591
  cmake/radium_setup_functions.cmake
Labels: Build System, GUI, High priority
