Repository STORM-IRIT/Radium-Engine, pull requests merged in 2021-01, with the labels that each got.

#643 [io] TinyPlyLoader refactor and cppcheck fix.
  src/IO/TinyPlyLoader/TinyPlyFileLoader.cpp
Labels: IO, Ready to merge, bug

#644 Intergration/Cache/Coverage
  .github/workflows/pull-request-ci.yml
  CMakeLists.txt
  README.md
  cmake/Config.cmake.in
  cmake/Windeployqt.cmake
  cmake/cleanCppExtensions.cmake
  cmake/radium_setup_functions.cmake
  doc/developer/buildchain.md
  doc/main.md
  src/CMakeLists.txt
  src/Core/CMakeLists.txt
  tests/CMakeLists.txt
  tests/ExampleApps/CMakeLists.txt
  tests/ExampleApps/CoreExampleApp/main.cpp
  tests/integration/CMakeLists.txt
  tests/integration/TinyPlyFileLoader/main.cpp
  tests/integration/data/inputs/buggy-1.ply
  tests/integration/data/inputs/simple.ply
  tests/integration/data/inputs/simple_normals.ply
  tests/integration/data/inputs/test_color_nonormals.ply
  tests/integration/data/inputs/test_color_normals.ply
  tests/integration/data/inputs/test_nocolor_normals.ply
  tests/integration/data/references/TinyPlyFileLoader.txt
  tests/unittest/CMakeLists.txt
Labels: Build System, WIP

#646 Fix windows external
  cmake/externalFunc.cmake
  src/Engine/CMakeLists.txt
  tests/CMakeLists.txt
Labels: Build System, High priority, Review In Progress, bug

#649 [Hotfix] Load radium_setup_functions at the beginning
  cmake/Config.cmake.in
Labels: Build System, bug

#648 Disable warning C4275 with MSVC
  src/Core/CoreMacros.hpp
Labels: Build System, Low priority

#650 Emphasis link with Radium-Release in readme
  README.md
Labels: documentation

#655 Resources
  .github/workflows/pull-request-ci.yml
  CMakeLists.txt
  README.md
  cmake/FindFilesystem.cmake
  cmake/coverageFunc.cmake
  cmake/messageFunc.cmake
  doc/basics/compilation.md
  src/Core/CMakeLists.txt
  src/Core/Resources/Resources.cpp
  src/Core/Resources/Resources.hpp
  src/Engine/RadiumEngine.cpp
  src/Engine/RadiumEngine.hpp
  src/Engine/Renderer/Material/BlinnPhongMaterial.cpp
  src/Engine/Renderer/Material/LambertianMaterial.cpp
  src/Engine/Renderer/Material/PlainMaterial.cpp
  src/Engine/Renderer/Material/SimpleMaterial.cpp
  src/Engine/Renderer/Material/VolumetricMaterial.cpp
  src/Engine/Renderer/RenderTechnique/ShaderConfiguration.cpp
  src/Engine/Renderer/Renderer.cpp
  src/Engine/Renderer/Renderers/ForwardRenderer.cpp
  src/Engine/Renderer/Texture/TextureManager.cpp
  src/Engine/Renderer/Texture/TextureManager.hpp
  src/GuiBase/BaseApplication.cpp
  src/GuiBase/BaseApplication.hpp
  src/GuiBase/Utils/KeyMappingManager.cpp
  tests/ExampleApps/CoreExampleApp/main.cpp
  tests/unittest/CMakeLists.txt
  tests/unittest/Core/resources.cpp
Labels: Build System, Core, Engine, Ready to merge, documentation, tests

#659 [github] Ugly fix for badge. Fix #652
  .github/workflows/deploy-doc.yml
  doc/CMakeLists.txt
Labels: Build System, Ready to merge, bug, documentation

#660 Unittest attrib
  CMakeLists.txt
  cmake/coverageFunc.cmake
  doc/developer/mesh.md
  tests/unittest/Core/mesh.cpp
Labels: Build System, Core, Review In Progress, WIP, tests

#662 Fix topo init
  src/Core/Geometry/TopologicalMesh.cpp
  src/Core/Geometry/TopologicalMesh.hpp
  tests/unittest/Core/topomesh.cpp
Labels: Core, bug, tests

#667 [github] remove mirror options.
  .github/workflows/pull-request-ci.yml
Labels: Ready to merge, github

#669 Fix #668
  doc/CMakeLists.txt
Labels: Ready to merge, bug, documentation
