Repository STORM-IRIT/Radium-Engine, pull requests merged in 2021-02, with the labels that each got.

#674 Enable assimp by default.
  .github/workflows/pull-request-ci.yml
  doc/basics/compilation.md
  src/IO/CMakeLists.txt
Labels: Build System, enhancement

#673 Engine init 3steps
  cmake/radium_setup_functions.cmake
  doc/concepts/plantUML/initEngineGL-polymorphic.puml
  src/Engine/RadiumEngine.cpp
  src/Engine/RadiumEngine.hpp
  src/Engine/Renderer/Material/BlinnPhongMaterial.cpp
  src/Engine/Renderer/Material/LambertianMaterial.cpp
  src/Engine/Renderer/Material/PlainMaterial.cpp
  src/Engine/Renderer/Material/VolumetricMaterial.cpp
  src/Engine/Renderer/RenderTechnique/RenderTechnique.cpp
  src/Engine/Renderer/RenderTechnique/ShaderConfiguration.cpp
  src/Engine/Renderer/RenderTechnique/ShaderProgramManager.cpp
  src/Engine/Renderer/RenderTechnique/ShaderProgramManager.hpp
  src/Engine/Renderer/Renderer.cpp
  src/Engine/Renderer/Renderer.hpp
  src/Engine/Renderer/Renderers/DebugRender.cpp
  src/Engine/Renderer/Renderers/ForwardRenderer.cpp
  src/GuiBase/BaseApplication.cpp
  src/GuiBase/BaseApplication.hpp
  src/GuiBase/MainWindowInterface.hpp
  src/GuiBase/RadiumWindow/SimpleWindow.cpp
  src/GuiBase/RadiumWindow/SimpleWindow.hpp
  src/GuiBase/Viewer/Viewer.cpp
  src/GuiBase/Viewer/Viewer.hpp
  src/GuiBase/Viewer/WindowQt.hpp
  tests/ExampleApps/CustomCameraManipulator/main.cpp
  tests/ExampleApps/DrawPrimitivesApp/minimalapp.cpp
  tests/ExampleApps/HelloRadium/main.cpp
  tests/ExampleApps/RawShaderMaterial/main.cpp
  tests/ExampleApps/SimpleAnimationApp/main.cpp
  tests/ExampleApps/SimpleSimulationApp/main.cpp
Labels: Engine, Feature Request, GUI, enhancement

#676 [tests] refactor mesh test
  src/Core/Utils/Attribs.cpp
  src/GuiBase/BaseApplication.cpp
  tests/unittest/Core/mesh.cpp
Labels: Core, refactor, tests

#675 First attempt to expose a functor to handle non-manifold elements
  src/Core/Geometry/TopologicalMesh.cpp
  src/Core/Geometry/TopologicalMesh.hpp
  src/Core/Geometry/TopologicalMesh.inl
  tests/unittest/Core/topomesh.cpp
Labels: enhancement

#679 Request for git when fetching externals
  cmake/ExternalInclude.cmake
  external/Core/CMakeLists.txt
  external/Engine/CMakeLists.txt
  external/IO/CMakeLists.txt
Labels: Build System, bug

#680 remove temporary files
  .ci/compile-official-plugins.sh
  .ci/qt-installer-noninteractive.qs
  src/Engine/class.txt
  src/Engine/list.txt
Labels: Ready to merge

#683 [cmake] Fix 682
  external/Core/CMakeLists.txt
  external/Engine/CMakeLists.txt
Labels: Build System, bug

#684 Add dependencies between external targets
  external/CMakeLists.txt
  external/Core/CMakeLists.txt
  external/Engine/CMakeLists.txt
  external/IO/CMakeLists.txt
Labels: Build System, bug

#689 Check if normals exists before accessing them (fix #688)
  src/Core/Geometry/TopologicalMesh.cpp
  src/Core/Geometry/TopologicalMesh.hpp
  src/Core/Geometry/TopologicalMesh.inl
  tests/unittest/Core/topomesh.cpp
Labels: Core, bug

#692 [github] Qt cache use cache@v1 (v2 is not compatible).
  .github/workflows/pull-request-ci.yml
Labels: Build System, enhancement

#695 Topo wedges
  doc/developer/mesh.md
  src/Core/Geometry/TopologicalMesh.cpp
  src/Core/Geometry/TopologicalMesh.hpp
  src/Core/Geometry/TopologicalMesh.inl
  tests/unittest/Core/topomesh.cpp
Labels: Core, bug

#696 fix #694: RawShaderMaterial naming convention, and integration target
  src/Engine/Data/RawShaderMaterial.cpp
  src/Engine/Data/RawShaderMaterial.hpp
  tests/integration/CMakeLists.txt
Labels: Build System, Engine, bug

#700 Fix engine namespace
  cmake/filelistEngine.cmake
  src/Engine/Data/BlinnPhongMaterial.hpp
  src/Engine/Data/DisplayableObject.hpp
  src/Engine/Data/Mesh.hpp
  src/Engine/Data/RenderParameters.hpp
  src/Engine/Data/ShaderProgramManager.hpp
  src/Engine/Data/ViewingParameters.hpp
  src/Engine/Data/VolumeObject.cpp
  src/Engine/Data/VolumeObject.hpp
  src/Engine/Data/VolumetricMaterial.hpp
  src/Engine/Rendering/ForwardRenderer.cpp
  src/Engine/Rendering/RenderObject.cpp
  src/Engine/Rendering/Renderer.cpp
  src/Gui/Viewer/Viewer.cpp
Labels: Engine, code style
