Repository STORM-IRIT/Radium-Engine, pull requests merged in 2022-02, with the labels that each got.

#861 Test doc
  .github/workflows/deploy-doc.yml
  doc/index/index.html
  doc/index/style.css
Labels: enhancement, documentation, Ready to merge

#865 [core] IndexLayer memory layout introspection
  doc/main.md
  src/Core/Asset/HandleData.inl
  src/Core/Asset/LightData.inl
  src/Core/Geometry/IndexedGeometry.hpp
  src/Core/Geometry/IndexedGeometry.inl
  src/Core/Utils/Attribs.cpp
  src/Core/Utils/Attribs.hpp
  src/Core/Utils/Attribs.inl
  src/Core/Utils/ContainerIntrospectionInterface.hpp
  src/Core/Utils/ObjectWithSemantic.hpp
  src/Engine/Data/Mesh.inl
  src/Engine/Scene/GeometrySystem.cpp
  src/Gui/Viewer/Viewer.cpp
  tests/unittest/Core/indexview.cpp
  tests/unittest/Core/observer.cpp
Labels: enhancement, Core, Ready to merge

#866 Add missing file in source list.
  cmake/filelistCore.cmake
  cmake/filelistIO.cmake
  src/Core/Utils/ContainerIntrospectionInterface.hpp
Labels: bug, Build System

#878 [cmake] First use robust deployqt and then fixup bundle
  .github/workflows/push-ci.yml
  cmake/RadiumSetupFunctions.cmake
Labels: bug, Build System
