Repository STORM-IRIT/Radium-Engine, pull requests merged in 2022-03, with the labels that each got.

#881 [headless] Fix installation issue and segfault when loading a scene with no camera
  tests/ExampleApps/HeadlessLibAndApp/Application/main.cpp
  tests/ExampleApps/HeadlessLibAndApp/libHeadless/Config.cmake.in
Labels: bug, Build System, demos

#877 Improve instruction first build
  doc/basics/dependencies.md
  external/Core/CMakeLists.txt
  external/Engine/CMakeLists.txt
  external/IO/CMakeLists.txt
Labels: Build System, documentation

#892 [doc] customize css to have visible menu carret
  doc/CMakeLists.txt
  doc/custom.css
Labels: enhancement, documentation

#894 Attempt to fix broken Qt installation in CI
  .github/workflows/build-matrix.yml
  .github/workflows/coverage.yml
  .github/workflows/pull-request-ci.yml
Labels: github

#889 [engine] add default to skinning switches.
  src/Engine/Scene/SkinningComponent.cpp
Labels: enhancement, Engine
